TI-125 Servicio de creación de paciente
RubenDelgadoPareja/TFG-Triaje-Inteligente-Consulta-Medica pull request #130
Opened 2024-07-19 19:57 UTC by RubenDelgadoPareja

Hemos creado un fichero en la capa de aplicación desde le cual podremos llamar al modelo de paciente gracias al nuevo repositorio creado. Esta forma de trabajar es típica de la estructura hexagonal para mantener la seguridad de cada capa.

2024-07-23 17:58 UTC, JJ requested changes
Recuerda mantener todo lo más simple posible.

2024-07-23 17:58 UTC, JJ commented on src/emergencyTriage/application/patientCreate.service.ts
> +export class PatientCreate {
Una clase es siempre un sustantivo, no un verbo. Las funciones son verbos.

2024-07-23 17:58 UTC, JJ commented on src/emergencyTriage/application/patientCreate.service.ts
> +  async execute(name: string, dni: string): Promise<Patient> {
¿Y por qué no es esto simplemente una función de PatientRepository?

2024-07-23 18:19 UTC, RubenDelgadoPareja commented on src/emergencyTriage/application/patientCreate.service.ts
> +  async execute(name: string, dni: string): Promise<Patient> {
La intención es utilizar el PatientRepository como una interfaz que conecte el dominio con el resto de capas

2024-07-23 18:36 UTC, JJ commented on src/emergencyTriage/application/patientCreate.service.ts
> +  async execute(name: string, dni: string): Promise<Patient> {
En DDD se habla de "entidades". ¿`PatientRepository` es una entidad? Si es así, puede perfectamente crear objetos valor.

2024-07-23 18:38 UTC, JJ requested changes
Aparte del typo, vamos otra vez a lo de siempre. ¿Va a haber varias implementaciones del interfaz? ¿Vas a separar "Services" de "Repository"? Trata siempre de usar como modelo la estructura más simple que te describa el problema.

2024-07-23 18:38 UTC, JJ commented on src/emergencyTriage/application/patient.repository.ts
> +import { IPatientRepository } from '../domain/repository/patiente.interface.respository';
typo en "respository"

2024-07-24 07:11 UTC, JJ requested changes
Deberíais tener en cuenta siempre por qué hacéis algo antes de hacerlo, para tener claro qué valor añadís al cliente. Tal como está planteado, ¿añade algún valor a simplemente llamar a un constructor? ¿Por qué no se puede llamar al constructor directamente desde donde sea?
Si usas DDD, tienes una vez más que considerar qué es un objeto valor (en este caso sería el paciente, ¿no?) y qué es una entidad y como gestiona el objeto valor. Tienes que pensar como las entidades trabajan con los objetos valor y al hacerlo qué valor añaden para el cliente.

2024-07-24 07:11 UTC, JJ commented on src/emergencyTriage/application/patient.services.ts
> +  async create(name: string, dni: string): Promise<Patient> {
¿Por qué es asíncrono?

2024-07-24 07:11 UTC, JJ commented on src/emergencyTriage/application/patient.services.ts
> +    return new Patient(name, dni);
¿Quién se encarga de gestionar ese paciente que se ha creado?

2024-07-24 15:38 UTC, RubenDelgadoPareja commented
> Deberíais tener en cuenta siempre por qué hacéis algo antes de hacerlo, para tener claro qué valor añadís al cliente. Tal como está planteado, ¿añade algún valor a simplemente llamar a un constructor? ¿Por qué no se puede llamar al constructor directamente desde donde sea? Si usas DDD, tienes una vez más que considerar qué es un objeto valor (en este caso sería el paciente, ¿no?) y qué es una entidad y como gestiona el objeto valor. Tienes que pensar como las entidades trabajan con los objetos valor y al hacerlo qué valor añaden para el cliente.

Estoy de acuerdo con que debe de aportar un valor directo al usuario y poder usar el constructor, pero el Paciente lo consideramos una entidad porque el DNI actuará como identificador único y por lo tanto le da una identidad a cada Paciente

2024-07-25 06:33 UTC, JJ commented
> > Deberíais tener en cuenta siempre por qué hacéis algo antes de hacerlo, para tener claro qué valor añadís al cliente. Tal como está planteado, ¿añade algún valor a simplemente llamar a un constructor? ¿Por qué no se puede llamar al constructor directamente desde donde sea? Si usas DDD, tienes una vez más que considerar qué es un objeto valor (en este caso sería el paciente, ¿no?) y qué es una entidad y como gestiona el objeto valor. Tienes que pensar como las entidades trabajan con los objetos valor y al hacerlo qué valor añaden para el cliente.
> 
> Estoy de acuerdo con que debe de aportar un valor directo al usuario y poder usar el constructor, pero el Paciente lo consideramos una entidad porque el DNI actuará como identificador único y por lo tanto le da una identidad a cada Paciente

¿Eso no lo hace ya el constructor?

2024-07-25 16:42 UTC, RubenDelgadoPareja commented
> Deberíais tener en cuenta siempre por qué hacéis algo antes de hacerlo, para tener claro qué valor añadís al cliente. Tal como está planteado, ¿añade algún valor a simplemente llamar a un constructor? ¿Por qué no se puede llamar al constructor directamente desde donde sea? Si usas DDD, tienes una vez más que considerar qué es un objeto valor (en este caso sería el paciente, ¿no?) y qué es una entidad y como gestiona el objeto valor. Tienes que pensar como las entidades trabajan con los objetos valor y al hacerlo qué valor añaden para el cliente.

No, realmente no añade ningún valor como tal al usuario final. Quizás estaba pensando erróneamente en usar los servicios como el conector o middleware entre la capa de dominio o su repositorio y la capa de infraestructura que accedería a la base de datos. La arquitectura hexagonal si puede aportar al usuario o al producto algo bueno pero nos saldríamos del desarrollo ágil  como tal.
Tengo que cambiar un poco la forma de pensar las cosas

2024-07-25 17:31 UTC, RubenDelgadoPareja commented
Se ha descartado por que no aporta valor al usuario y no realmente no se ha pensado correctamente antes de abrir la issue #125

2024-07-25 17:31 UTC, closed without merging